CREATE TABLE IF NOT EXISTS `cot_oembed_cache` (
  `oembed_id` int(11) NOT NULL AUTO_INCREMENT,
  `oembed_url` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `oembed_area` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `oembed_item` int(11) NOT NULL,
  `oembed_pageref` smallint(6) NOT NULL,
  `oembed_added` int(11) NOT NULL,
  `oembed_valid` tinyint(4) NOT NULL,
  `url` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `version` varchar(4) COLLATE utf8_unicode_ci NOT NULL,
  `title` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `author_name` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `author_url` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `provider_name` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `provider_url` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `cache_age` int(11) NOT NULL,
  `width` smallint(6) NOT NULL,
  `height` smallint(6) NOT NULL,
  `thumbnail_url` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `thumbnail_width` smallint(6) NOT NULL,
  `thumbnail_height` smallint(6) NOT NULL,
  `html` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`oembed_id`),
  KEY `oembed_area` (`oembed_area`,`oembed_item`,`oembed_pageref`),
  KEY `oembed_added` (`oembed_added`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;